import { Document, Page, View, Text } from "@react-pdf/renderer";
import { COLORS } from "./styles";
import type { MasterRow } from "@/lib/masterlist";

const COLS: { key: keyof MasterRow; label: string; w: number }[] = [
  { key: "welderName", label: "Welder", w: 90 },
  { key: "uid", label: "UID", w: 70 },
  { key: "welderId", label: "Welder ID", w: 48 },
  { key: "process", label: "Process", w: 60 },
  { key: "jointType", label: "Joint", w: 32 },
  { key: "position", label: "Pos.", w: 34 },
  { key: "materialGroups", label: "Mat. grp", w: 50 },
  { key: "thicknessRange", label: "Thickness", w: 64 },
  { key: "pipeOdRange", label: "Pipe OD", w: 52 },
  { key: "status", label: "Status", w: 54 },
  { key: "issued", label: "Issued", w: 56 },
  { key: "expiry", label: "Expiry", w: 56 },
  { key: "revalidation", label: "Reval", w: 36 },
];

const HAIR = 0.5;

export function MasterListDocument({
  rows,
  orgName,
}: {
  rows: MasterRow[];
  orgName: string;
}) {
  return (
    <Document title="Welder Master List" author={orgName}>
      <Page
        size="A4"
        orientation="landscape"
        style={{ padding: 22, fontFamily: "Helvetica" }}
      >
        <View
          style={{
            flexDirection: "row",
            justifyContent: "space-between",
            borderBottomWidth: 1.5,
            borderBottomColor: COLORS.onyx,
            paddingBottom: 5,
            marginBottom: 6,
          }}
        >
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 12, color: COLORS.onyx }}>
            {orgName}
          </Text>
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 10, color: COLORS.onyx }}>
            WELDER QUALIFICATION MASTER LIST — EN ISO 9606-1
          </Text>
          <Text style={{ fontSize: 8 }}>
            {new Date().toLocaleDateString("en-GB")}
          </Text>
        </View>

        <View style={{ flexDirection: "row", backgroundColor: COLORS.frost }}>
          <Cell w={20} header>
            #
          </Cell>
          {COLS.map((c) => (
            <Cell key={c.key} w={c.w} header>
              {c.label}
            </Cell>
          ))}
        </View>

        {rows.map((r, i) => (
          <View key={i} style={{ flexDirection: "row" }} wrap={false}>
            <Cell w={20}>{String(i + 1)}</Cell>
            {COLS.map((c) => (
              <Cell key={c.key} w={c.w}>
                {String(r[c.key] ?? "—")}
              </Cell>
            ))}
          </View>
        ))}

        <Text style={{ marginTop: 8, fontSize: 7, color: COLORS.steel }}>
          {rows.length} record(s) · Generated by WeldDoc
        </Text>
      </Page>
    </Document>
  );
}

function Cell({
  w,
  header,
  children,
}: {
  w: number;
  header?: boolean;
  children: React.ReactNode;
}) {
  return (
    <View
      style={{
        width: w,
        padding: 2.5,
        borderWidth: HAIR,
        borderColor: COLORS.silver,
      }}
    >
      <Text
        style={{
          fontSize: 6.5,
          fontFamily: header ? "Helvetica-Bold" : "Helvetica",
          color: header ? COLORS.graphite : COLORS.onyx,
        }}
      >
        {children}
      </Text>
    </View>
  );
}
