import { Document, Page, View, Text } from "@react-pdf/renderer";
import { COLORS } from "./styles";
import {
  MASTER_EXPORT_COLUMNS,
  formatMasterRowExport,
  type MasterExportKey,
  type MasterRow,
} from "@/lib/masterlist";

const COL_WIDTHS: Record<MasterExportKey, number> = {
  slNo: 16,
  welderName: 52,
  welderNo: 28,
  process: 44,
  jointType: 22,
  actualBwPosition: 26,
  actualFwPosition: 26,
  qualifiedBwPosition: 34,
  qualifiedFwPosition: 34,
  fmGroup: 22,
  qualifiedDia: 30,
  qualifiedBwThk: 34,
  qualifiedFwThk: 34,
  testDate: 38,
  continuityExpiry: 38,
  revalidationExpiry: 38,
};

const HAIR = 0.5;

export function MasterListDocument({
  rows,
  orgName,
}: {
  rows: MasterRow[];
  orgName: string;
}) {
  return (
    <Document title="Welder Master List" author={orgName}>
      <Page
        size="A4"
        orientation="landscape"
        style={{ padding: 16, fontFamily: "Helvetica" }}
      >
        <View
          style={{
            flexDirection: "row",
            justifyContent: "space-between",
            borderBottomWidth: 1.5,
            borderBottomColor: COLORS.onyx,
            paddingBottom: 5,
            marginBottom: 6,
          }}
        >
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 12, color: COLORS.onyx }}>
            {orgName}
          </Text>
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 10, color: COLORS.onyx }}>
            WELDER QUALIFICATION MASTER LIST — EN ISO 9606-1
          </Text>
          <Text style={{ fontSize: 8 }}>
            {new Date().toLocaleDateString("en-GB")}
          </Text>
        </View>

        <View style={{ flexDirection: "row", backgroundColor: COLORS.frost }}>
          {MASTER_EXPORT_COLUMNS.map((c) => (
            <Cell key={c.key} w={COL_WIDTHS[c.key]} header>
              {c.label}
            </Cell>
          ))}
        </View>

        {rows.map((r, i) => (
          <View key={i} style={{ flexDirection: "row" }} wrap={false}>
            {MASTER_EXPORT_COLUMNS.map((c) => (
              <Cell key={c.key} w={COL_WIDTHS[c.key]}>
                {formatMasterRowExport(c.key, r, i + 1)}
              </Cell>
            ))}
          </View>
        ))}

        <Text style={{ marginTop: 8, fontSize: 7, color: COLORS.steel }}>
          {rows.length} record(s) · Generated by Weld.Doc
        </Text>
      </Page>
    </Document>
  );
}

function Cell({
  w,
  header,
  children,
}: {
  w: number;
  header?: boolean;
  children: React.ReactNode;
}) {
  return (
    <View
      style={{
        width: w,
        padding: 2,
        borderWidth: HAIR,
        borderColor: COLORS.silver,
      }}
    >
      <Text
        style={{
          fontSize: header ? 5.2 : 5,
          fontFamily: header ? "Helvetica-Bold" : "Helvetica",
          color: header ? COLORS.graphite : COLORS.onyx,
        }}
      >
        {children}
      </Text>
    </View>
  );
}
