import { Document, Page, View, Text } from "@react-pdf/renderer";
import { COLORS } from "./styles";
import {
  formatOperatorMasterRowExport,
  type OperatorMasterRow,
} from "@/lib/operator-masterlist";
import type { OperatorMasterColumnKey } from "@/lib/masterlist/operator-columns";

const COL_WIDTHS: Partial<Record<OperatorMasterColumnKey, number>> = {
  slNo: 20,
  operatorName: 84,
  operatorId: 44,
  process: 40,
  standard: 36,
  weldingType: 48,
  productType: 52,
  jointType: 36,
  weldingMode: 44,
  rangeSummary: 120,
  status: 48,
  issued: 52,
  expiry: 52,
  revalidation: 32,
};

const DEFAULT_COL_WIDTH = 40;
const HAIR = 0.5;

function colWidth(key: OperatorMasterColumnKey): number {
  return COL_WIDTHS[key] ?? DEFAULT_COL_WIDTH;
}

export function OperatorMasterListDocument({
  rows,
  columns,
  orgName,
}: {
  rows: OperatorMasterRow[];
  columns: { key: OperatorMasterColumnKey; label: string }[];
  orgName: string;
}) {
  return (
    <Document title="Operator Master List" author={orgName}>
      <Page
        size="A4"
        orientation="landscape"
        style={{ padding: 22, fontFamily: "Helvetica" }}
      >
        <View
          style={{
            flexDirection: "row",
            justifyContent: "space-between",
            borderBottomWidth: 1.5,
            borderBottomColor: COLORS.onyx,
            paddingBottom: 5,
            marginBottom: 6,
          }}
        >
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 12, color: COLORS.onyx }}>
            {orgName}
          </Text>
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 10, color: COLORS.onyx }}>
            OPERATOR QUALIFICATION MASTER LIST — ISO 14732:2025
          </Text>
          <Text style={{ fontSize: 8 }}>
            {new Date().toLocaleDateString("en-GB")}
          </Text>
        </View>

        <View style={{ flexDirection: "row", backgroundColor: COLORS.frost }}>
          {columns.map((c) => (
            <Cell key={c.key} w={colWidth(c.key)} header>
              {c.label}
            </Cell>
          ))}
        </View>

        {rows.map((r, i) => (
          <View key={i} style={{ flexDirection: "row" }} wrap={false}>
            {columns.map((c) => (
              <Cell key={c.key} w={colWidth(c.key)}>
                {formatOperatorMasterRowExport(c.key, r, i + 1)}
              </Cell>
            ))}
          </View>
        ))}

        <Text style={{ marginTop: 8, fontSize: 7, color: COLORS.steel }}>
          {rows.length} record(s) · Generated by Weld.Doc
        </Text>
      </Page>
    </Document>
  );
}

function Cell({
  w,
  header,
  children,
}: {
  w: number;
  header?: boolean;
  children: React.ReactNode;
}) {
  return (
    <View
      style={{
        width: w,
        padding: 2.5,
        borderWidth: HAIR,
        borderColor: COLORS.silver,
      }}
    >
      <Text
        style={{
          fontSize: 6.5,
          fontFamily: header ? "Helvetica-Bold" : "Helvetica",
          color: header ? COLORS.graphite : COLORS.onyx,
        }}
      >
        {children}
      </Text>
    </View>
  );
}
